trigger:
- master

pool:
  name: WindowVm

variables:
  containerRegistry: 'azuredb2acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/Dockerfile'
  imageName: 'biradarsandeepsamplejavaapp'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: '$(containerRegistry)/$(imageName)'
    Dockerfile: '$(dockerfilePath)'
    tags: |
      $(tag)
  env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1
