trigger:
- main

pool:
  name: WindowVm

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '21.0.2'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean install -X'  # Add -X for verbose output
      displayName: 'Maven Build'

    - task: CopyFiles@2
      inputs:
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
      displayName: 'Copy JAR files'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Build
  pool:
    name: WindowVm
  steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Pay-As-You-Go (3f9425f7-b0f9-40b7-9c23-beca0c6a8610)-1210'
        appType: 'webApp'
        WebAppName: 'azuredb2-web-app'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.jar'
      displayName: 'Deploy to Azure Web App'
